services:
  rag-api:
    logging:
     driver: loki
     options:
     loki-url: "http://loki:3100/loki/api/v1/push"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    restart: unless-stopped

  celery_worker:
    logging:
     driver: loki
     options:
     loki-url: "http://loki:3100/loki/api/v1/push"
    build: .
    deploy:
      mode: replicated
      replicas: 1
    command: celery -A celery_config:celery_app worker --loglevel=info --concurrency=1
    depends_on:
      - redis
    restart: unless-stopped


  redis:
    image: redis:7-alpine
    ports: #[]
      - "6379:6379"
    restart: unless-stopped
  
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    restart: unless-stopped


  
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-rag_db}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  flower:
    image: mher/flower
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - FLOWER_UNAUTHENTICATED_API=true
    depends_on:
      - redis
      - celery_worker
    restart: unless-stopped  

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./monitoring/loki:/etc/loki
      - loki_data:/loki


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki

  ollama:
    image: ollama/ollama
    ports: 
      - "11434:11434"  # Ollama API port   
    environment:
      MODEL: "deepseek-coder:1.3b"
    volumes:
      - ollama-data:/root/.ollama  # Persist models
      - ./etc/:/etc

    entrypoint: ["etc/entrypoint.sh"]

  frontend:
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
    build:
      context: ./frontend
      dockerfile: DockerFile
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://rag-api:8000
    depends_on:
      - rag-api
 
volumes:
  ollama-data:
  prometheus_data:
  loki_data:
  grafana_data:
  postgres_data: